language: python
matrix:
    include:
        - os: linux
          python: 3.6
        - os: linux
          language: generic
          env: PYTHON="3.7" MINICONDA_OS="Linux"
        - os: linux
          python: nightly
    allow_failures:
        - python: "nightly"

cache:
    directories:
      - $HOME/.cache/pip
      - .hypothesis

before_install:
  - if [[ $MINICONDA_OS ]]; then
      URL="https://repo.continuum.io/miniconda/Miniconda3-latest-${MINICONDA_OS}-x86_64.sh";
      wget "${URL}" -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda;
      export PATH="$HOME/miniconda/bin:$PATH";
      hash -r;
      conda config --set always_yes yes --set changeps1 no;
      conda update -q conda;
      conda info -a;
      conda create -q -n test-environment python=$PYTHON;
      source activate test-environment;
    fi;

install:
  - pip install -e .;
  - pip install mypy;
  
script:
  - mypy ppb_mutant
